### ISSUE TITLE
Find a real name

### ISSUE THREAD

**Issue by ZynoXelek** [iScsc/Haunted-Chronicles#9]
Find a real name for the game.

**Comment by BlueNZ** [comment]
SquaresOnline or GhostOnline

**Comment by BlueNZ** [comment]
HideAndSeekOnline

**Comment by BlueNZ** [comment]
GhostSeekers

**Comment by ZynoXelek** [comment]
Haunted Chronicles

**Comment by BlueNZ** [comment]
Haunted Mansion

**Comment by ZynoXelek** [comment]
> Haunted Chronicles

What do you think about it @AChauvin78 @Shisohka @Laudut ?
